# Generated by Django 5.2.17 on 2026-09-11 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="index_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="index_status",
            field=models.CharField(
                choices=[
                    ("NOT_INDEXED", "Not Indexed"),
                    ("INDEXING", "Indexing"),
                    ("INDEXED", "Indexed"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_INDEXED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="index_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerinteraction",
            name="escalated_call",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_interactions",
                to="core.servicecall",
            ),
        ),
    ]
