# Generated by Django 6.0.3 on 2026-09-24 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_knowledgedocument_index_error_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticPlaybook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "applicability_tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated symptom or model tags",
                        max_length=500,
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        default=dict,
                        help_text="Structured graph containing nodes, transitions, and validation rules",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_playbooks",
                        to="core.productcategory",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_playbooks",
                        to="core.productdomain",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_playbooks",
                        to="core.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "name"],
                "unique_together": {("tenant", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosticSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("playbook_version", models.PositiveIntegerField(default=1)),
                (
                    "complaint",
                    models.TextField(
                        help_text="Original complaint or symptom reported by customer"
                    ),
                ),
                ("current_node_id", models.CharField(default="start", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("WAITING_INPUT", "Waiting Input"),
                            ("WAITING_VERIFY", "Waiting Verify"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version for optimistic concurrency",
                    ),
                ),
                ("facts_snapshot", models.JSONField(blank=True, default=dict)),
                ("evidence_completeness", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_sessions",
                        to="core.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_diagnostic_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_sessions",
                        to="core.customer",
                    ),
                ),
                (
                    "escalated_call",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_session",
                        to="core.servicecall",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="core.diagnosticplaybook",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_sessions",
                        to="core.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecoveryPassport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint", models.TextField()),
                (
                    "structured_data",
                    models.JSONField(
                        default=dict,
                        help_text="Deterministic diagnostic evidence, observations, and outcomes",
                    ),
                ),
                (
                    "do_not_repeat_items",
                    models.JSONField(
                        default=list,
                        help_text="Verified actions and checks that should not be repeated",
                    ),
                ),
                ("evidence_completeness", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_passports",
                        to="core.asset",
                    ),
                ),
                (
                    "service_call",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_passport",
                        to="core.servicecall",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_passport",
                        to="core.diagnosticsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_num", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=60)),
                ("actor_role", models.CharField(default="customer", max_length=30)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.diagnosticsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "seq_num"],
                "unique_together": {("session", "seq_num")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosticCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                ("command_type", models.CharField(max_length=60)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveIntegerField(default=200)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="core.diagnosticsession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "idempotency_key"],
                        name="core_diagno_tenant__7478dc_idx",
                    )
                ],
                "unique_together": {("tenant", "idempotency_key")},
            },
        ),
    ]
