# Generated by Django 6.0.3 on 2026-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_diagnosticplaybook_diagnosticsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcommand",
            name="state",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="COMPLETED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcommand",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="diagnosticsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("WAITING_INPUT", "Waiting Input"),
                    ("WAITING_VERIFY", "Waiting Verify"),
                    ("RESOLVED", "Resolved"),
                    ("ESCALATED", "Escalated"),
                    ("ABANDONED", "Abandoned"),
                    ("NO_PLAYBOOK_AVAILABLE", "No Playbook Available"),
                ],
                default="ACTIVE",
                max_length=30,
            ),
        ),
    ]
